### ISSUE TITLE
how to map the transdecoder output gff file to genome coordinate

### ISSUE THREAD

**Issue by lijing28101** [TransDecoder/TransDecoder#103]
Hi, the transdecoder output is based on the transcript coordinate. I have the the gtf file for transcript coordinate in genome. How can I map the CDS gff file from transdecoder to the genome coordinate?

Thanks,
Jing

**Comment by brianjohnhaas** [comment]
Hi Jing,

Check out the example provided under:  TransDecoder/sample_data/pasa_example

It uses a transcript fasta file and the genome alignment coordinates as I
expect you want to.

best,

~b

On Wed, Apr 1, 2020 at 10:17 PM lijing28101 <notifications@github.com>
wrote:
>
> Hi, the transdecoder output is based on the transcript coordinate. I have
the the gtf file for transcript coordinate in genome. How can I map the CDS
gff file from transdecoder to the genome coordinate?
>
> Thanks,
> Jing
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas
