### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Axze-rgb** [TransDecoder/TransDecoder#126]
Hello,

I get this error 
when runninf TransDecoder.Predict

`seqlogo module not found
`
The output *.pep file is produced anyway, is it harmless?

**Comment by brianjohnhaas** [comment]
what's the error msg?

**Comment by Axze-rgb** [comment]
That one 
I did not see anything else

**Comment by brianjohnhaas** [comment]
oh, the message didn't show up in the email, but on github it's fine.

You can ignore the seqlogo msg.  If you have the R module seqlogo installed, it'll make use of it to make some plots, but it's not essential.

**Comment by Axze-rgb** [comment]
Ok thanks!
