### ISSUE TITLE
Document that Transdecoder creates duplicate FASTA entries in .mRNA files and eventually fix the behavior

### ISSUE THREAD

**Issue by mmokrejs** [TransDecoder/TransDecoder#13]
Hi Brian,
  you asked me to open a ticked in https://groups.google.com/d/msgid/transdecoder-users/cc43e733-f626-40da-b977-6be58dcb129d%40googlegroups.com 

  The documentation terribly lacks description what is in the .mRNA/.cds/.pep file and how they relate to original input.

  It turns out in the .mRNA file there are multiple entries derived from same input FASTA record entry whenever more than one non-overlapping ORF was found by transdecoder. They however retain original strand orientation (which is unexpected IMHO). They should be oriented into 'plus', as should be the .cds file. I don't believe the .pep files respects the original input file orientation (inconsistency).

  Of course, provided Transdecoder used quite some resources to run the hmmsearch and blastp searches it is a pitty it does not return output in plus (sense) orientation.

Hope this helps,
Martin

**Comment by brianjohnhaas** [comment]
mRNA file generation for standard (genome-free) transdecoder is now deprecated.
