### ISSUE TITLE
Improve formatting of a FASTA description line

### ISSUE THREAD

**Issue by mmokrejs** [TransDecoder/TransDecoder#14]
Hi Brian,
  I appreciate that Transdecoder records a lot of information in the FASTA description line but, provided the first word (up to first whitespace) is veeeeery looooong and contains unusual chars, at least I do something about the following to yield usable identifiers:

sed -e 's/,length=/ /g' -i *.(mRNA|cds|pep)

  You mentioned in https://groups.google.com/d/msgid/transdecoder-users/cc43e733-f626-40da-b977-6be58dcb129d%40googlegroups.com that Transdecoder does not report if there are duplicate FASTA entries in the input, actually it messes up internally but does not exit with a clear message.

  My naive alteration of the formatting clearly has a potential to create duplicated accessions, and per the google group I am not the only one. Moreover, only thorough users are going to realize the mess in the output.

  Please ensure Transdecoder output unique IDs and in a generally acceptable format (no commas, no pipe symbols or brackets). Currently there is (should be shown on github on a single line but is not):

`>contig_101119,length=299,cov=4.1,gc=0.378|m.3901 contig_101119,length=299,cov=4.1,gc=0.378|g.3901  ORF contig_101119,length=299,cov=4.1,gc=0.378|g.3901 contig_101119,length=299,cov=4.1,gc=0.378|m.3901 type:internal len:100 (-) contig_101119,length=299,cov=4.1,gc=0.378:1-297(-)`

  I do not know why pieces of the information are repeated on the line. It just makes it hard to read/use.

  Please test your final formatting with a tool like 'formatdb' from an ncbi-tools bundle (aka blast).

Hope this helps,
Martin

**Comment by brianjohnhaas** [comment]
fixed
