### ISSUE TITLE
change the directory to write the final output

### ISSUE THREAD

**Issue by manuelsmendoza** [TransDecoder/TransDecoder#143]
Maybe it possible to change the directory where Transrate writes the final output? By now it's the working directory and, in my opinion it'd be a good idea change that and write the final output in the output directory option (if passed).

**Comment by brianjohnhaas** [comment]
This gets a bit tricky based on how the code is currently organized.

Would be best to just 
  cd /path/to/output/dir

and then run TransDecoder with the full path to your target transcriptome that lies outside of this output directory.
