### ISSUE TITLE
Ugly string format in gff3 after using conversion utils?

### ISSUE THREAD

**Issue by Andy-B-123** [TransDecoder/TransDecoder#155]
Hi, I am having persistent formatting issues when I use conversion utils? I am running transdecoder version 5.5.0. 

I have a .gtf file generated from merging multiple Stringtie gtf files:
`> head temp.txt.gtf`
![image](https://user-images.githubusercontent.com/35752341/183549237-0c82a6c2-2f9f-4fd8-9879-526b0295c27e.png)

but running the gtf -> gff3 util introduces this '^' character:
`> /apps/transdecoder/5.5.0/util/gtf_to_alignment_gff3.pl temp.txt.gtf`
![image](https://user-images.githubusercontent.com/35752341/183549547-b780c542-45e4-4d88-946f-05a9592da682.png)

I thought this might be fine, but the end gff3 is also incorrectly formatted, containing lots of '%20' type codes, which I think are utf-8 codes? 
![image](https://user-images.githubusercontent.com/35752341/183550939-0ea48612-cbfc-4a7e-a82c-27f63f35d599.png)

The .bed, .pep and .cds are fine though?
![image](https://user-images.githubusercontent.com/35752341/183550999-6b837c7e-e549-4787-929b-f3947a572786.png)

I was able to manually replace them with a sed script but it's a bit funky. I think this is an encoding issue but I'm not sure exactly how to trouble-shoot it? 

Also just wanted to mention this in case anyone else has the same problem! Here is the sed script for replacing the funky characters
```
#!/bin/bash
echo 'Input file: ' $1
output_file=${1/.gff3/.clean.gff3}
echo 'Output file: ' $output_file

sed 's/%20/_/g' $1 > $output_file
sed -i 's/%3A/:/g' $output_file
sed -i 's/%28/(/g' $output_file
sed -i 's/%29/)/g' $output_file
sed -i 's/%2B/+/g' $output_file
sed -i 's/%2C/,/g' $output_file
sed -i 's/%3D/=/g' $output_file
sed -i 's/%7C/|/g' $output_file
```

**Comment by brianjohnhaas** [comment]
will be turning off the uri-encoding in the upcoming release
