### ISSUE TITLE
Document what Transdecoder outputs if there is an assembly chimera in input data

### ISSUE THREAD

**Issue by mmokrejs** [TransDecoder/TransDecoder#16]
In myfile.fasta I may have:

```
>myaccession assembly chimera: 5'-gene1-polyA-polyT-rc_gene2-3'
...
```

Blastp is likely to find two matches but on opposite strands. Transdecoder could also find the corresponding ORF on both strands. So what is output then?

As you said it split the record into multiple if there are more disparate ORF found. so in myfile.mRNA there would be something like the following currently (ignore the myaccession replaced for clarity):
```
>gene1-polyA ORF:11-100
...
>polyT-rc_gene2 ORF:1110-1200
...
```

How is the split position determined by Transdecoder? The two ORF do not overlap, there is quite some sequence in between them actually. Where does it cut to make two entries in .mRNA file if in input was just one, long sequence?

I would have preferred:

In myfile.mRNA:
```
>myaccession [ORF:11-100 [PFAM:Pfam0001; BLASTP: unknown protein], ORF:1110-1200 [PFAM: Pfam0002; BLASTP: conserved protein]]
...
```

In myfile.cds:
```
>myaccession_ORF:11-100_CDS:1-30
...
>myaccession_ORF:1110-1200_CDS:1-30
...
```

In myfile.pep:
```
>myaccession_ORF:11-100_PEP:1-10
....
>myaccession_ORF:1110-1200_PEP:1-10
...
```

Inspired by original report at https://groups.google.com/d/msgid/transdecoder-users/86b76db3-3a4e-438f-9750-c9c0d45baa26%40googlegroups.com.

**Comment by mmokrejs** [comment]
Here is an example of a contig from a transcriptomic assembly (no mis-assembly, just testing what happens in common cases). The ORF is on the minus strand, btw.

```
>contig_101119,length=299,cov=4.1,gc=0.378
TCTTTGCAAAACCCCAATGCACTGATGATAAAGTTCAAGTGGGAATTTTTTCATCATGTGCGATGTAATGAATTCAACAAGCAAATCAAGTAATGTAGCAGCCAATGGTTGTACAGGTGCTGTTTTATCTTGAATCTTCCTGTGATGCATTGGTACTCTATGAAGCTGAACTCTGAAAGCCAAGTTTGCATCATGCATCAAGCTATTTGCGTACTGATCTTCCGCGATGCAGCTTAATATAAGGAAGCACAATTTGACATTACTCATTATTGCTTCTGTTCTGATAACTTGCATAACta
```

Currently Transdecoder-2.0.1 stores in .cds files just the ORF sequence which length can be divided by three -- it removes leading and trailing nucleotides of the original .mRNA sequence if they do not contribute to the reading frame.

In the .mRNA file I received sequence flipped by Transdecoder-2.0.1 into sense orientation, great!:
```
>contig_101119,length=299,cov=4.1,gc=0.378|m.3901 contig_101119,length=299,cov=4.1,gc=0.378|g.3901  ORF contig_101119,length=299,cov=4.1,gc=0.378|g.3901 contig_101119,length=299,cov=4.1,gc=0.378|m.3901 type:internal len:100 (-) contig_101119,length=299,cov=4.1,gc=0.378:1-297(-)
taGTTATGCAAGTTATCAGAACAGAAGCAATAATGAGTAATGTCAAATTGTGCTTCCTTA
TATTAAGCTGCATCGCGGAAGATCAGTACGCAAATAGCTTGATGCATGATGCAAACTTGG
CTTTCAGAGTTCAGCTTCATAGAGTACCAATGCATCACAGGAAGATTCAAGATAAAACAG
CACCTGTACAACCATTGGCTGCTACATTACTTGATTTGCTTGTTGAATTCATTACATCGC
ACATGATGAAAAAATTCCCACTTGAACTTTATCATCAGTGCATTGGGGTTTTGCAAAGA
```

Although it seems because of the trailing "1-297(-)" that the ORF is located on the minus strand, it is not true. Transdecoder-2.0.1 already did that for .mRNA/.cds files so do NOT interpret these "(-)" as a hint you should orient the .mRNA/.cds files yourself.
Note: The initiator ATG is now at position 6-8.
Note: The original input sequence was 1-299 so the last 2 nucleotides did not belong to ORF (5'-...at-'3'). That is true, the sequence in .cds file lacks the first two nucleotides (5'-ta....-3'). 

So Transdecoder discards leading "ta" while writing out .cds file.


And finally, here is the .pep file content:

```
>contig_101119,length=299,cov=4.1,gc=0.378|m.3901 contig_101119,length=299,cov=4.1,gc=0.378|g.3901  ORF contig_101119,length=299,cov=4.1,gc=0.378|g.3901 contig_101119,length=299,cov=4.1,gc=0.378|m.3901 type:internal len:100 (-) contig_101119,length=299,cov=4.1,gc=0.378:1-297(-)
VMQVIRTEAIMSNVKLCFLILSCIAEDQYANSLMHDANLAFRVQLHRVPMHHRKIQDKTA
PVQPLAATLLDLLVEFITSHMMKKFPLELYHQCIGVLQR
```

**Comment by mmokrejs** [comment]
In the case below Transdecoder-2.0.1 did not yield any blastp match and also had no pfam hits (not shown). However, in the FASTA description line of .mRNA file shown below you can see `(+)`. I do not know where even the `type:5prime_partial` comes from because a blastn search through predicted genes of honeybee [NM_001242519.1](https://www.ncbi.nlm.nih.gov/nuccore/335892836) shows it is actually matching 998-1311 of that predicted transcript. -- So is this a 3'-UTR instead? Shall I conclude a bad default value kicked in? Further, the `3-317(+)` would be a non-sense ... But hey, read further.

```
>contig_10651 length=500,cov=13.9,gc=0.298|m.1449 contig_10651,length=500,cov=13.9,gc=0.298|g.1449  ORF contig_10651,length=500,cov=13.9,gc=0.298|g.1449 contig_10651,length=500,cov=13.9,gc=0.298|m.1449 type:5prime_partial len:105 (+) contig_10651,length=500,cov=13.9,gc=0.298:3-317(+)
atTTGTTATTTTGGCAACTTACGGTTCAAATTTCACATTATTTTTACATTGCTGCAACTA
TGTACAGCTTAATCGACATAATGTTTGCTTCAGTATCACTGTTGATTCACATATATTTCG
TTTTCATTTTTACTGGCATTACATTAACGGTTGTAGCATATATGTACTGTGTAGTTGACT
TTACAAAAATTTATTTATATATATTTACGAAAGTAAGAAAATACGAAACGACACAGGAAT
TATTATTCAATGATGATAAACATAATCATTTTAAGTTACGAGATTTTTTAGATGTAATGG
GTTGGGCTAGCTCTTGAGCAGGAGGGACAAGGAAGTTAAGTTTATAACTATCGATATTAA
GGTAATAATCGTACAGATGATTTTTTGCTTCATATATATATGTGTAAATTAGTTTTTTTA
GCTGTTTATTATTATGTAAAAGGTGAGCTGCATGTATTTCCTTTATGTTCTTCGTATCAA
TGGATGGTACTTCAGTGGCG

```

Actually here _ab initio_ prediction of Transdecoder-2.0.1 kicked in and it found an real ORF. In the above .mRNA there is ORF `60-317` (`ATG...TGA`). Transdecoder-2.0.1 predicts rather longer N-terminus so the annotated ORF range is indeed `3-317` (`TTG...TGA`). From that perspective, it makes sense to annotate `type:5prime_partial`.

**Comment by brianjohnhaas** [comment]
The .cds files provide the translatable sequence starting from the first base of the first translatable codon.  If there's a partial codon upstream due to a 5' partial, then these bases get ignored in the .cds report (and will show up as a false 1 or 2 base UTR in the gff3 file).  I think it's fine for now.  

I'm dropping the .mRNA file writing as part of the process, since it just leads to general confusion, a lot of redundancy in the multi-orf case, and due to the conflicting info in the header that get's carried over to it.
