### ISSUE TITLE
substr outside of string at TransDecoder-2.1.0/util/../PerlLib/Gene_obj.pm line 1315.

### ISSUE THREAD

**Issue by mmokrejs** [TransDecoder/TransDecoder#18]
It seems for crappy contigs this is reported several times per each. I do not understand the english in there but probably there is no ORF found in the particular contig. UPDATE: the contigs had same FASTA ID but it is not enough by itself to trigger the issue. However, altering teh IDs makes the perl issues go away.

```
substr outside of string at TransDecoder-2.1.0/util/../PerlLib/Gene_obj.pm line 1315.
Use of uninitialized value in concatenation (.) or string at TransDecoder-2.1.0/util/../PerlLib/Gene_obj.pm line 1315.
No incoming CDS sequence to set to
        asmbl_id:       contig26635
        Model_feat_name:        contig26635|m.37251
        num_exons:      1
        gene_type:      protein-coding
        is_pseudogene:  0
        TU_feat_name:   contig26635|g.37251
        classification: annotated_genes
        strand: -
        is_5prime_partial:      0
        is_3prime_partial:      0
        com_name:       ORF contig26635|g.37251 contig26635|m.37251 type:complete len:323 (-)
        source: transdecoder
        mid_pt: 4423
        gene_length:    8846
        gene_synonyms:
        mRNA_coords
        CDS_coords
                RNA-exon: 8846, 1       CDS-exon: 7952, 6984
        gene_span: 8846-1
        model_span: 7952-6984
```

I initially received this with transdecoder-2.0.1 so it is not a new issue.

**Comment by brianjohnhaas** [comment]
If you can send me the data this is happening on, I'll take a look directly.

thx,

~b

On Fri, Apr 1, 2016 at 11:26 AM, mmokrejs <notifications@github.com> wrote:

> It seems for crappy contigs this is reported 3x per each. I do not
> understand the english in there but probably there is no ORF found in the
> particular contig. Why i is printed only 3x instead of 6x I do not know.
>
> substr outside of string at TransDecoder-2.1.0/util/../PerlLib/Gene_obj.pm line 1315.
> Use of uninitialized value in concatenation (.) or string at TransDecoder-2.1.0/util/../PerlLib/Gene_obj.pm line 1315.
> No incoming CDS sequence to set to
>         asmbl_id:       contig26635
>         Model_feat_name:        contig26635|m.37251
>         num_exons:      1
>         gene_type:      protein-coding
>         is_pseudogene:  0
>         TU_feat_name:   contig26635|g.37251
>         classification: annotated_genes
>         strand: -
>         is_5prime_partial:      0
>         is_3prime_partial:      0
>         com_name:       ORF contig26635|g.37251 contig26635|m.37251 type:complete len:323 (-)
>         source: transdecoder
>         mid_pt: 4423
>         gene_length:    8846
>         gene_synonyms:
>         mRNA_coords
>         CDS_coords
>                 RNA-exon: 8846, 1       CDS-exon: 7952, 6984
>         gene_span: 8846-1
>         model_span: 7952-6984
>
> I initially received this with transdecoder-2.0.1 so it is not a new issue.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/TransDecoder/TransDecoder/issues/18>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by mmokrejs** [comment]
Thanks Brian, you can link this to issue #13 , create

**Comment by brianjohnhaas** [comment]
let's reopen it if it's still an issue.
