### ISSUE TITLE
Is v3.0.0 a real release or still a pre-release/beta?

### ISSUE THREAD

**Issue by mr-c** [TransDecoder/TransDecoder#24]
https://github.com/TransDecoder/TransDecoder/releases/tag/v3.0.0

I'm trying to figure out if the Debian package should be updated or not. Thanks.

**Comment by brianjohnhaas** [comment]
Hi Michael,

I just turned it into a regular release.

thx,

~brian

On Tue, May 17, 2016 at 5:55 AM, Michael R. Crusoe <notifications@github.com
> wrote:

> https://github.com/TransDecoder/TransDecoder/releases/tag/v3.0.0
>
> I'm trying to figure out if the Debian package should be updated or not.
> Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/TransDecoder/TransDecoder/issues/24>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
