### ISSUE TITLE
TransDecoder.Predict problem

### ISSUE THREAD

**Issue by rafalwoycicki** [TransDecoder/TransDecoder#25]
Dear All,

I realized that though in TransDecoder.LongOrfs we can choose the specific genetic code and than we have the proteins producing properly, so TransDecoder.Predict does not take the specific genetic coed into account (does not have the option to set) and is producing peptides with a lot of STOP codons, like in my Cilliate example. I can than of course take just the names of proteins and extract these from the LongOrfs output but would be better for a pipeline if Predict also would take the different codes into consideration.

Would you be able to add the Genetic Code option to Predict?

Thank you and Best regards,
Rafal

**Comment by brianjohnhaas** [comment]
Hi Rafal,

I'll do this tomorrow.  Thanks for your patience.

~b

On Wed, Jun 29, 2016 at 11:37 AM, Rafal Woycicki <notifications@github.com>
wrote:

> Dear All,
>
> I realized that though in TransDecoder.LongOrfs we can choose the specific
> genetic code and than we have the proteins producing properly, so
> TransDecoder.Predict does not take the specific genetic coed into account
> (does not have the option to set) and is producing peptides with a lot of
> STOP codons, like in my Cilliate example. I can than of course take just
> the names of proteins and extract these from the LongOrfs output but would
> be better for a pipeline if Predict also would take the different codes
> into consideration.
>
> Would you be able to add the Genetic Code option to Predict?
>
> Thank you and Best regards,
> Rafal
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TransDecoder/TransDecoder/issues/25>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AHMVX6WifRFzRbKIQz3Tu6Lb29iWj7z_ks5qQpFAgaJpZM4JBRUr>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by rafalwoycicki** [comment]
Thank you Brian!

Rafal

**Comment by brianjohnhaas** [comment]
Hi Rafal,

Can you try pulling the code from here:

https://github.com/TransDecoder/TransDecoder

The updated TransDecoder.Predict should have an option like
TransDecoder.LongOrfs for setting the genetic code.

Let''s see if it works ok for you now.  If it doesn't, it would help me to
have an example data set to run through to verify it works w/ the alt
genetic code setting.

best,

~b

**Comment by rafalwoycicki** [comment]
Thank you Brian!
I will check it out today and will let you know !

Best,
Rafal
