### ISSUE TITLE
Counting number of candidate coding regions

### ISSUE THREAD

**Issue by browngcm** [TransDecoder/TransDecoder#42]
I've used TransDecoder as part of the Trinotate annotation suite. I was wondering if there is a way to get a count of the number of candidate coding regions from the TransDecoder output files. Maybe I'm missing something....

Thanks!

**Comment by brianjohnhaas** [comment]
Hi

The easiest thing to do is to just count the number of predicted proteins 

   grep '>' transdecoder.pep | wc -l

-Brian
(by iPhone)

**Comment by MGCBrown** [comment]
Thank you!
