### ISSUE TITLE
Error in Transdocer

### ISSUE THREAD

**Issue by biomichal** [TransDecoder/TransDecoder#56]
Hi
When I run my data, a problem occurred as the following:
Running CMD: /export/software/Genome_annotation/transdecoder/TransDecoder-v5.0.2/util/PWM/deplete_feature_noise.pl  --features_plus pasa_assemblies.fasta.transdecoder_dir/start_refinement.+.features  --pwm_minus pasa_assemblies.fasta.transdecoder_dir/start_refinement.-.pwm  --out_prefix pasa_assemblies.fasta.transdecoder_dir/start_refinement.enhanced
num features: 3	num_incorporate: 0
Error, len(target_sequence)=33 and pwm length = 0 at 
/export/software/Genome_annotation/transdecoder/TransDecoder-v5.0.2/util/PWM/deplete_feature_noise.pl line 116.
Error, cmd: /export/software/Genome_annotation/transdecoder/TransDecoder-v5.0.2/util/PWM/deplete_feature_noise.pl  --features_plus pasa_assemblies.fasta.transdecoder_dir/start_refinement.+.features  --pwm_minus pasa_assemblies.fasta.transdecoder_dir/start_refinement.-.pwm  --out_prefix pasa_assemblies.fasta.transdecoder_dir/start_refinement.enhanced died with ret 65280 at /export/software/Genome_annotation/transdecoder/TransDecoder-v5.0.2/util/../PerlLib/Pipeliner.pm line 166.
	Pipeliner::run('Pipeliner=HASH(0x220e0d8)') called at /export/software/Genome_annotation/transdecoder/TransDecoder-v5.0.2/util/train_start_PWM.pl line 141
Error, cmd: /export/software/Genome_annotation/transdecoder/TransDecoder-v5.0.2/util/train_start_PWM.pl --transcripts pasa_assemblies.fasta --selected_orfs pasa_assemblies.fasta.transdecoder_dir/longest_orfs.cds.top_500_longest --out_prefix pasa_
assemblies.fasta.transdecoder_dir/start_refinement died with ret 512 at /export/software/Genome_annotation/transdecoder/TransDecoder-v5.0.2/PerlLib/Pipeliner.pm line 166.
	Pipeliner::run('Pipeliner=HASH(0x29fd730)') called at /export/software/Genome_annotation/transdecoder/current/TransDecoder.Predict line 321

I don’t know where is the problem. Can you help me？

**Comment by brianjohnhaas** [comment]
Hi,

If the data set is very small, then this kind of problem can arise.  If you
run it with

 --no_refine_starts


then it should complete ok.


best,


~b


On Wed, Mar 7, 2018 at 1:56 AM, biomichal <notifications@github.com> wrote:
>
> Hi
> When I run my data, a problem occurred as the following:
>
> Running CMD:
/export/software/Genome_annotation/transdecoder/TransDecoder-v5.0.2/util/PWM/
deplete_feature_noise.pl --features_plus
pasa_assemblies.fasta.transdecoder_dir/start_refinement.+.features
--pwm_minus pasa_assemblies.fasta.transdecoder_dir/start_refinement.-.pwm
--out_prefix
pasa_assemblies.fasta.transdecoder_dir/start_refinement.enhanced
> num features: 3 num_incorporate: 0
> Error, len(target_sequence)=33 and pwm length = 0 at
>
>
/export/software/Genome_annotation/transdecoder/TransDecoder-v5.0.2/util/PWM/
deplete_feature_noise.pl line 116.
> Error, cmd:
/export/software/Genome_annotation/transdecoder/TransDecoder-v5.0.2/util/PWM/
deplete_feature_noise.pl --features_plus
pasa_assemblies.fasta.transdecoder_dir/start_refinement.+.features
--pwm_minus pasa_assemblies.fasta.transdecoder_dir/start_refinement.-.pwm
--out_prefix
pasa_assemblies.fasta.transdecoder_dir/start_refinement.enhanced died with
ret 65280 at
/export/software/Genome_annotation/transdecoder/TransDecoder-v5.0.2/util/../PerlLib/Pipeliner.pm
line 166.
> Pipeliner::run('Pipeliner=HASH(0x220e0d8)') called at
/export/software/Genome_annotation/transdecoder/TransDecoder-v5.0.2/util/train_start_PWM.pl
line 141
> Error, cmd:
/export/software/Genome_annotation/transdecoder/TransDecoder-v5.0.2/util/train_start_PWM.pl
--transcripts pasa_assemblies.fasta --selected_orfs
pasa_assemblies.fasta.transdecoder_dir/longest_orfs.cds.top_500_longest
--out_prefix pasa_
> assemblies.fasta.transdecoder_dir/start_refinement died with ret 512 at
/export/software/Genome_annotation/transdecoder/TransDecoder-v5.0.2/PerlLib/Pipeliner.pm
line 166.
> Pipeliner::run('Pipeliner=HASH(0x29fd730)') called at
/export/software/Genome_annotation/transdecoder/current/TransDecoder.Predict
line 321
>
> I don’t know where is the problem. Can you help me？
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.




--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by biomichal** [comment]
Yeah, It really works, and thanks very much.
