### ISSUE TITLE
Error in Longorfs if sequence_id is a "0"

### ISSUE THREAD

**Issue by ctcncgr** [TransDecoder/TransDecoder#59]
The program errors after creating base_freqs.dat during orf prediction:

"Error, no asmbl_id from gene_obj"

I am almost positive this is because of this conditional from "Gene_obj.pm" evaluating false when the capture is "0" (i.e. the sequence line is something like ">0 whatever whatever_else"):

unless ($asmbl_id) {
        if ($gene_id =~ /^(\d+)/) {
            $asmbl_id = $1;
        } else {
            die "Error, no asmbl_id from gene_obj\n";
        }
    }

Relabeling the sequence with a string prefixing all of the sequence_ids fixed this error and the program completes.

Thank you

**Comment by prabodh11180** [comment]
Hi
I am facing the same while running transdecoder.....
error message: Error, no asmbl_id from gene_obj
My sequence id starts as: >c4014_g1_i1 len=430 path=[53:0-429]

please help me, if you have found the solution....
thanks
Prabodh
