### ISSUE TITLE
Where are the genetic codes?

### ISSUE THREAD

**Issue by Will338** [TransDecoder/TransDecoder#9]
Is there a list of genetic codes anywhere which there are options for within TransDecoder? Seems like it was once at this link but doesn't work anymore: http://golgi.harvard.edu/biolinks/gencode.html

**Comment by brianjohnhaas** [comment]
I found it in the time machine:

https://web.archive.org/web/20091014073539/http://golgi.harvard.edu/BioLinks/gencode.html

I'll add it to our documentation for safe keeping.

~b

On Fri, Dec 4, 2015 at 9:30 AM, Will338 <notifications@github.com> wrote:

> Is there a list of genetic codes anywhere which there are options for
> within TransDecoder? Seems like it was once at this link but doesn't work
> anymore: http://golgi.harvard.edu/biolinks/gencode.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TransDecoder/TransDecoder/issues/9>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by Will338** [comment]
Cheers!
