### ISSUE TITLE
Wiki Page: -S flag should be for TransDecoder.LongOrfs not TransDecoder.Predict

### ISSUE THREAD

**Issue by ckeeling** [TransDecoder/TransDecoder#93]
Just a confusion in the wiki page documentation, Step 3: predict the likely coding regions.  The information about using the -S flag should be at Step 1: extract the long open reading frames.  It is TransDecoder.LongOrfs, not TransDecoder.Predict, that takes this flag.

**Comment by brianjohnhaas** [comment]
documentation updated - better late than never. :-)
